version: "3"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  graphql:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "4000:4000"

  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"
