version: "3"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MAX_CONNECTIONS: 200
    networks:
      - my-network
    ports:
      - "5432:5432"

  graphql:
    build: ./backend
    depends_on:
      - postgres
    networks:
      - my-network
    ports:
      - "4000:4000"

  nextjs:
    build: ./frontend
    networks:
      - my-network
    ports:
      - "3000:3000"

networks:
  my-network:
